FROM docker.elastic.co/elasticsearch/elasticsearch:8.2.1

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-kuromoji
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu